"""Add recall tracking fields to vehicles

Revision ID: 4da8cc82426d
Revises: 
Create Date: 2026-04-27 10:46:54.960785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da8cc82426d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recall_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recall_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_vehicle_user_vin', ['user_id', 'vin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vehicle_user_vin', type_='unique')
        batch_op.drop_column('recall_count')
        batch_op.drop_column('recall_checked_at')

    # ### end Alembic commands ###
